// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxrAriOwH_9G34oNLzBRvn8fpQWWasxUY',
    appId: '1:768402911610:web:8613cb9676a530875666c3',
    messagingSenderId: '768402911610',
    projectId: 'my-notes-projects2',
    authDomain: 'my-notes-projects2.firebaseapp.com',
    storageBucket: 'my-notes-projects2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr-JDjjg1551f6NAYWYfU3oecmmsUCnK4',
    appId: '1:768402911610:android:40b8613089e9f57f5666c3',
    messagingSenderId: '768402911610',
    projectId: 'my-notes-projects2',
    storageBucket: 'my-notes-projects2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNuS8YARwyxYEbu5DK53dBCmr81nKBbgA',
    appId: '1:768402911610:ios:5cf6d14f345acd255666c3',
    messagingSenderId: '768402911610',
    projectId: 'my-notes-projects2',
    storageBucket: 'my-notes-projects2.appspot.com',
    iosClientId: '768402911610-ob0rjv8vbf62f53ccmdcrc2vl2ceq2bp.apps.googleusercontent.com',
    iosBundleId: 'com.example.app2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNuS8YARwyxYEbu5DK53dBCmr81nKBbgA',
    appId: '1:768402911610:ios:5cf6d14f345acd255666c3',
    messagingSenderId: '768402911610',
    projectId: 'my-notes-projects2',
    storageBucket: 'my-notes-projects2.appspot.com',
    iosClientId: '768402911610-ob0rjv8vbf62f53ccmdcrc2vl2ceq2bp.apps.googleusercontent.com',
    iosBundleId: 'com.example.app2',
  );
}
